#include <sys/bus.h>

ANTARES_FBSD_DRIVER_GLUE(atheros813x, alc, pci);

ANTARES_FBSD_MII_DRIVER(ukphy);
ANTARES_DRIVER_REQUIREMENTS(FBSD_TASKQUEUES | FBSD_FAST_TASKQUEUE);
NO_ANTARES_CHECK_DISABLE_INTERRUPTS();
NO_ANTARES_REENABLE_INTERRUPTS();
