#include <sys/bus.h>

ANTARES_FBSD_DRIVER_GLUE(ipro1000, em, pci)

NO_ANTARES_CHECK_DISABLE_INTERRUPTS();
NO_ANTARES_REENABLE_INTERRUPTS();
NO_ANTARES_FBSD_MII_DRIVER();

#ifdef EM_FAST_INTR
	ANTARES_DRIVER_REQUIREMENTS(FBSD_TASKQUEUES | FBSD_FAST_TASKQUEUE);
#else
	ANTARES_DRIVER_REQUIREMENTS(0);
#endif
